project_id = "qwdukyhuyhjbzbbvoixp"

[functions.seed-services]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.newsletter-subscribe]
verify_jwt = false

[functions.ccpa-request]
verify_jwt = false

[functions.contact-submit]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.backup-database]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = false